// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kubediscovery/v1/analyzer.proto

package analyzerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnalysisRequest carries Kubernetes incident context to kd-analyzer.
type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ClusterName   string                 `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResourceKind  string                 `protobuf:"bytes,6,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	ResourceName  string                 `protobuf:"bytes,7,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	PodPhase      string                 `protobuf:"bytes,8,opt,name=pod_phase,json=podPhase,proto3" json:"pod_phase,omitempty"`
	LogLines      []string               `protobuf:"bytes,9,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`
	EventMessages []string               `protobuf:"bytes,10,rep,name=event_messages,json=eventMessages,proto3" json:"event_messages,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_kubediscovery_v1_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalysisRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AnalysisRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *AnalysisRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *AnalysisRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AnalysisRequest) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

func (x *AnalysisRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *AnalysisRequest) GetPodPhase() string {
	if x != nil {
		return x.PodPhase
	}
	return ""
}

func (x *AnalysisRequest) GetLogLines() []string {
	if x != nil {
		return x.LogLines
	}
	return nil
}

func (x *AnalysisRequest) GetEventMessages() []string {
	if x != nil {
		return x.EventMessages
	}
	return nil
}

func (x *AnalysisRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalysisRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

// MemoryKey identifies the semantic indexing partition used by kd-store.
type MemoryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Environment   string                 `protobuf:"bytes,2,opt,name=environment,proto3" json:"environment,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryKey) Reset() {
	*x = MemoryKey{}
	mi := &file_kubediscovery_v1_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryKey) ProtoMessage() {}

func (x *MemoryKey) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryKey.ProtoReflect.Descriptor instead.
func (*MemoryKey) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryKey) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *MemoryKey) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *MemoryKey) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MemoryKey) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// AnalysisResult returns diagnosis, severity and recommendations from kd-analyzer.
type AnalysisResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Diagnosis       string                 `protobuf:"bytes,2,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	Severity        string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Recommendations []string               `protobuf:"bytes,4,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Summary         string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	AnalysisRef     string                 `protobuf:"bytes,6,opt,name=analysis_ref,json=analysisRef,proto3" json:"analysis_ref,omitempty"`
	MemoryKey       *MemoryKey             `protobuf:"bytes,7,opt,name=memory_key,json=memoryKey,proto3" json:"memory_key,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	AnalyzedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=analyzed_at,json=analyzedAt,proto3" json:"analyzed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_kubediscovery_v1_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalysisResult) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *AnalysisResult) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AnalysisResult) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *AnalysisResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalysisResult) GetAnalysisRef() string {
	if x != nil {
		return x.AnalysisRef
	}
	return ""
}

func (x *AnalysisResult) GetMemoryKey() *MemoryKey {
	if x != nil {
		return x.MemoryKey
	}
	return nil
}

func (x *AnalysisResult) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalysisResult) GetAnalyzedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnalyzedAt
	}
	return nil
}

var File_kubediscovery_v1_analyzer_proto protoreflect.FileDescriptor

const file_kubediscovery_v1_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x1fkubediscovery/v1/analyzer.proto\x12\x10kubediscovery.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x03\n" +
	"\x0fAnalysisRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterName\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12#\n" +
	"\rresource_kind\x18\x06 \x01(\tR\fresourceKind\x12#\n" +
	"\rresource_name\x18\a \x01(\tR\fresourceName\x12\x1b\n" +
	"\tpod_phase\x18\b \x01(\tR\bpodPhase\x12\x1b\n" +
	"\tlog_lines\x18\t \x03(\tR\blogLines\x12%\n" +
	"\x0eevent_messages\x18\n" +
	" \x03(\tR\reventMessages\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12;\n" +
	"\vobserved_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\x84\x01\n" +
	"\tMemoryKey\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12 \n" +
	"\venvironment\x18\x02 \x01(\tR\venvironment\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\xfe\x02\n" +
	"\x0eAnalysisResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tdiagnosis\x18\x02 \x01(\tR\tdiagnosis\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12(\n" +
	"\x0frecommendations\x18\x04 \x03(\tR\x0frecommendations\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12!\n" +
	"\fanalysis_ref\x18\x06 \x01(\tR\vanalysisRef\x12:\n" +
	"\n" +
	"memory_key\x18\a \x01(\v2\x1b.kubediscovery.v1.MemoryKeyR\tmemoryKey\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12;\n" +
	"\vanalyzed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"analyzedAtB>Z<github.com/kubediscovery/kd-libs/core/v1/analyzer;analyzerv1b\x06proto3"

var (
	file_kubediscovery_v1_analyzer_proto_rawDescOnce sync.Once
	file_kubediscovery_v1_analyzer_proto_rawDescData []byte
)

func file_kubediscovery_v1_analyzer_proto_rawDescGZIP() []byte {
	file_kubediscovery_v1_analyzer_proto_rawDescOnce.Do(func() {
		file_kubediscovery_v1_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubediscovery_v1_analyzer_proto_rawDesc), len(file_kubediscovery_v1_analyzer_proto_rawDesc)))
	})
	return file_kubediscovery_v1_analyzer_proto_rawDescData
}

var file_kubediscovery_v1_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kubediscovery_v1_analyzer_proto_goTypes = []any{
	(*AnalysisRequest)(nil),       // 0: kubediscovery.v1.AnalysisRequest
	(*MemoryKey)(nil),             // 1: kubediscovery.v1.MemoryKey
	(*AnalysisResult)(nil),        // 2: kubediscovery.v1.AnalysisResult
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_kubediscovery_v1_analyzer_proto_depIdxs = []int32{
	3, // 0: kubediscovery.v1.AnalysisRequest.metadata:type_name -> google.protobuf.Struct
	4, // 1: kubediscovery.v1.AnalysisRequest.observed_at:type_name -> google.protobuf.Timestamp
	1, // 2: kubediscovery.v1.AnalysisResult.memory_key:type_name -> kubediscovery.v1.MemoryKey
	3, // 3: kubediscovery.v1.AnalysisResult.metadata:type_name -> google.protobuf.Struct
	4, // 4: kubediscovery.v1.AnalysisResult.analyzed_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kubediscovery_v1_analyzer_proto_init() }
func file_kubediscovery_v1_analyzer_proto_init() {
	if File_kubediscovery_v1_analyzer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubediscovery_v1_analyzer_proto_rawDesc), len(file_kubediscovery_v1_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubediscovery_v1_analyzer_proto_goTypes,
		DependencyIndexes: file_kubediscovery_v1_analyzer_proto_depIdxs,
		MessageInfos:      file_kubediscovery_v1_analyzer_proto_msgTypes,
	}.Build()
	File_kubediscovery_v1_analyzer_proto = out.File
	file_kubediscovery_v1_analyzer_proto_goTypes = nil
	file_kubediscovery_v1_analyzer_proto_depIdxs = nil
}
