// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kubediscovery/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentStreamMessage_Hello
	//	*AgentStreamMessage_Heartbeat
	//	*AgentStreamMessage_Command
	//	*AgentStreamMessage_CommandResult
	Payload       isAgentStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamMessage) Reset() {
	*x = AgentStreamMessage{}
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamMessage) ProtoMessage() {}

func (x *AgentStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamMessage.ProtoReflect.Descriptor instead.
func (*AgentStreamMessage) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AgentStreamMessage) GetPayload() isAgentStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentStreamMessage) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentStreamMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentStreamMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetCommand() *GatewayCommand {
	if x != nil {
		if x, ok := x.Payload.(*AgentStreamMessage_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *AgentStreamMessage) GetCommandResult() *AgentCommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentStreamMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isAgentStreamMessage_Payload interface {
	isAgentStreamMessage_Payload()
}

type AgentStreamMessage_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentStreamMessage_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentStreamMessage_Command struct {
	Command *GatewayCommand `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type AgentStreamMessage_CommandResult struct {
	CommandResult *AgentCommandResult `protobuf:"bytes,4,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*AgentStreamMessage_Hello) isAgentStreamMessage_Payload() {}

func (*AgentStreamMessage_Heartbeat) isAgentStreamMessage_Payload() {}

func (*AgentStreamMessage_Command) isAgentStreamMessage_Payload() {}

func (*AgentStreamMessage_CommandResult) isAgentStreamMessage_Payload() {}

type AgentHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical agent identifier (self-reported, used as mapping key in memory).
	CallerId string `protobuf:"bytes,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	// Untrusted free-form metadata for diagnostics.
	Metadata *structpb.Struct `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Time when the hello frame was generated by the agent.
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AgentHello) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *AgentHello) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AgentHello) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type AgentHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CallerId      string                 `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHeartbeat) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentHeartbeat) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *AgentHeartbeat) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type GatewayCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TargetCallerId string                 `protobuf:"bytes,2,opt,name=target_caller_id,json=targetCallerId,proto3" json:"target_caller_id,omitempty"`
	Operation      string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Payload        *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayCommand) Reset() {
	*x = GatewayCommand{}
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCommand) ProtoMessage() {}

func (x *GatewayCommand) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCommand.ProtoReflect.Descriptor instead.
func (*GatewayCommand) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GatewayCommand) GetTargetCallerId() string {
	if x != nil {
		return x.TargetCallerId
	}
	return ""
}

func (x *GatewayCommand) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *GatewayCommand) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayCommand) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type AgentCommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CallerId      string                 `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	RespondedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=responded_at,json=respondedAt,proto3" json:"responded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommandResult) Reset() {
	*x = AgentCommandResult{}
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommandResult) ProtoMessage() {}

func (x *AgentCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommandResult.ProtoReflect.Descriptor instead.
func (*AgentCommandResult) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *AgentCommandResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentCommandResult) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *AgentCommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentCommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentCommandResult) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentCommandResult) GetRespondedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RespondedAt
	}
	return nil
}

var File_kubediscovery_v1_gateway_proto protoreflect.FileDescriptor

const file_kubediscovery_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1ekubediscovery/v1/gateway.proto\x12\x10kubediscovery.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x02\n" +
	"\x12AgentStreamMessage\x124\n" +
	"\x05hello\x18\x01 \x01(\v2\x1c.kubediscovery.v1.AgentHelloH\x00R\x05hello\x12@\n" +
	"\theartbeat\x18\x02 \x01(\v2 .kubediscovery.v1.AgentHeartbeatH\x00R\theartbeat\x12<\n" +
	"\acommand\x18\x03 \x01(\v2 .kubediscovery.v1.GatewayCommandH\x00R\acommand\x12M\n" +
	"\x0ecommand_result\x18\x04 \x01(\v2$.kubediscovery.v1.AgentCommandResultH\x00R\rcommandResultB\t\n" +
	"\apayload\"\x93\x01\n" +
	"\n" +
	"AgentHello\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\tR\bcallerId\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x123\n" +
	"\asent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\x81\x01\n" +
	"\x0eAgentHeartbeat\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\tR\bcallerId\x123\n" +
	"\asent_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xdf\x01\n" +
	"\x0eGatewayCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12(\n" +
	"\x10target_caller_id\x18\x02 \x01(\tR\x0etargetCallerId\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xf6\x01\n" +
	"\x12AgentCommandResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\tR\bcallerId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12=\n" +
	"\fresponded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vrespondedAt2o\n" +
	"\x0eGatewayService\x12]\n" +
	"\vAgentStream\x12$.kubediscovery.v1.AgentStreamMessage\x1a$.kubediscovery.v1.AgentStreamMessage(\x010\x01B<Z:github.com/kubediscovery/kd-libs/core/v1/gateway;gatewayv1b\x06proto3"

var (
	file_kubediscovery_v1_gateway_proto_rawDescOnce sync.Once
	file_kubediscovery_v1_gateway_proto_rawDescData []byte
)

func file_kubediscovery_v1_gateway_proto_rawDescGZIP() []byte {
	file_kubediscovery_v1_gateway_proto_rawDescOnce.Do(func() {
		file_kubediscovery_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubediscovery_v1_gateway_proto_rawDesc), len(file_kubediscovery_v1_gateway_proto_rawDesc)))
	})
	return file_kubediscovery_v1_gateway_proto_rawDescData
}

var file_kubediscovery_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_kubediscovery_v1_gateway_proto_goTypes = []any{
	(*AgentStreamMessage)(nil),    // 0: kubediscovery.v1.AgentStreamMessage
	(*AgentHello)(nil),            // 1: kubediscovery.v1.AgentHello
	(*AgentHeartbeat)(nil),        // 2: kubediscovery.v1.AgentHeartbeat
	(*GatewayCommand)(nil),        // 3: kubediscovery.v1.GatewayCommand
	(*AgentCommandResult)(nil),    // 4: kubediscovery.v1.AgentCommandResult
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_kubediscovery_v1_gateway_proto_depIdxs = []int32{
	1,  // 0: kubediscovery.v1.AgentStreamMessage.hello:type_name -> kubediscovery.v1.AgentHello
	2,  // 1: kubediscovery.v1.AgentStreamMessage.heartbeat:type_name -> kubediscovery.v1.AgentHeartbeat
	3,  // 2: kubediscovery.v1.AgentStreamMessage.command:type_name -> kubediscovery.v1.GatewayCommand
	4,  // 3: kubediscovery.v1.AgentStreamMessage.command_result:type_name -> kubediscovery.v1.AgentCommandResult
	5,  // 4: kubediscovery.v1.AgentHello.metadata:type_name -> google.protobuf.Struct
	6,  // 5: kubediscovery.v1.AgentHello.sent_at:type_name -> google.protobuf.Timestamp
	6,  // 6: kubediscovery.v1.AgentHeartbeat.sent_at:type_name -> google.protobuf.Timestamp
	5,  // 7: kubediscovery.v1.GatewayCommand.payload:type_name -> google.protobuf.Struct
	6,  // 8: kubediscovery.v1.GatewayCommand.sent_at:type_name -> google.protobuf.Timestamp
	5,  // 9: kubediscovery.v1.AgentCommandResult.payload:type_name -> google.protobuf.Struct
	6,  // 10: kubediscovery.v1.AgentCommandResult.responded_at:type_name -> google.protobuf.Timestamp
	0,  // 11: kubediscovery.v1.GatewayService.AgentStream:input_type -> kubediscovery.v1.AgentStreamMessage
	0,  // 12: kubediscovery.v1.GatewayService.AgentStream:output_type -> kubediscovery.v1.AgentStreamMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_kubediscovery_v1_gateway_proto_init() }
func file_kubediscovery_v1_gateway_proto_init() {
	if File_kubediscovery_v1_gateway_proto != nil {
		return
	}
	file_kubediscovery_v1_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentStreamMessage_Hello)(nil),
		(*AgentStreamMessage_Heartbeat)(nil),
		(*AgentStreamMessage_Command)(nil),
		(*AgentStreamMessage_CommandResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubediscovery_v1_gateway_proto_rawDesc), len(file_kubediscovery_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubediscovery_v1_gateway_proto_goTypes,
		DependencyIndexes: file_kubediscovery_v1_gateway_proto_depIdxs,
		MessageInfos:      file_kubediscovery_v1_gateway_proto_msgTypes,
	}.Build()
	File_kubediscovery_v1_gateway_proto = out.File
	file_kubediscovery_v1_gateway_proto_goTypes = nil
	file_kubediscovery_v1_gateway_proto_depIdxs = nil
}
