// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kubediscovery/v1/mcp.proto

package mcpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecuteToolRequest carries a normalized MCP tool invocation.
type ExecuteToolRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CallerId       string                 `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	TargetCallerId string                 `protobuf:"bytes,3,opt,name=target_caller_id,json=targetCallerId,proto3" json:"target_caller_id,omitempty"`
	ToolName       string                 `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ClusterName    string                 `protobuf:"bytes,5,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Environment    string                 `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	Namespace      string                 `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// MCP tool arguments as free-form JSON-like structure.
	Arguments *structpb.Struct `protobuf:"bytes,8,opt,name=arguments,proto3" json:"arguments,omitempty"`
	// Additional context about the MCP client/session.
	Metadata      *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolRequest) Reset() {
	*x = ExecuteToolRequest{}
	mi := &file_kubediscovery_v1_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolRequest) ProtoMessage() {}

func (x *ExecuteToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolRequest.ProtoReflect.Descriptor instead.
func (*ExecuteToolRequest) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteToolRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteToolRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *ExecuteToolRequest) GetTargetCallerId() string {
	if x != nil {
		return x.TargetCallerId
	}
	return ""
}

func (x *ExecuteToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteToolRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ExecuteToolRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ExecuteToolRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExecuteToolRequest) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ExecuteToolRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteToolRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

// ExecuteToolResponse returns command execution output for MCP tool calls.
type ExecuteToolResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ToolName  string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Success   bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Structured payload returned by kd-agent/kd-executor.
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolResponse) Reset() {
	*x = ExecuteToolResponse{}
	mi := &file_kubediscovery_v1_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolResponse) ProtoMessage() {}

func (x *ExecuteToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolResponse.ProtoReflect.Descriptor instead.
func (*ExecuteToolResponse) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteToolResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteToolResponse) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteToolResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteToolResponse) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteToolResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ExecuteToolResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecuteToolResponse) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// AnalyzeClusterRequest asks kd-gateway to orchestrate a diagnosis request.
type AnalyzeClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CallerId      string                 `protobuf:"bytes,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	ClusterName   string                 `protobuf:"bytes,3,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResourceKind  string                 `protobuf:"bytes,6,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	ResourceName  string                 `protobuf:"bytes,7,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	PodPhase      string                 `protobuf:"bytes,8,opt,name=pod_phase,json=podPhase,proto3" json:"pod_phase,omitempty"`
	LogLines      []string               `protobuf:"bytes,9,rep,name=log_lines,json=logLines,proto3" json:"log_lines,omitempty"`
	EventMessages []string               `protobuf:"bytes,10,rep,name=event_messages,json=eventMessages,proto3" json:"event_messages,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeClusterRequest) Reset() {
	*x = AnalyzeClusterRequest{}
	mi := &file_kubediscovery_v1_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeClusterRequest) ProtoMessage() {}

func (x *AnalyzeClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeClusterRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeClusterRequest) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeClusterRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeClusterRequest) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *AnalyzeClusterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *AnalyzeClusterRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *AnalyzeClusterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AnalyzeClusterRequest) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

func (x *AnalyzeClusterRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *AnalyzeClusterRequest) GetPodPhase() string {
	if x != nil {
		return x.PodPhase
	}
	return ""
}

func (x *AnalyzeClusterRequest) GetLogLines() []string {
	if x != nil {
		return x.LogLines
	}
	return nil
}

func (x *AnalyzeClusterRequest) GetEventMessages() []string {
	if x != nil {
		return x.EventMessages
	}
	return nil
}

func (x *AnalyzeClusterRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalyzeClusterRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

// AnalyzeClusterResponse returns analysis details for MCP clients.
type AnalyzeClusterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Diagnosis       string                 `protobuf:"bytes,3,opt,name=diagnosis,proto3" json:"diagnosis,omitempty"`
	Severity        string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Recommendations []string               `protobuf:"bytes,5,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	Summary         string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	AnalysisRef     string                 `protobuf:"bytes,7,opt,name=analysis_ref,json=analysisRef,proto3" json:"analysis_ref,omitempty"`
	MemoryKey       string                 `protobuf:"bytes,8,opt,name=memory_key,json=memoryKey,proto3" json:"memory_key,omitempty"`
	Metadata        *structpb.Struct       `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,10,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message         string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`
	AnalyzedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=analyzed_at,json=analyzedAt,proto3" json:"analyzed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeClusterResponse) Reset() {
	*x = AnalyzeClusterResponse{}
	mi := &file_kubediscovery_v1_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeClusterResponse) ProtoMessage() {}

func (x *AnalyzeClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeClusterResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeClusterResponse) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeClusterResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeClusterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnalyzeClusterResponse) GetDiagnosis() string {
	if x != nil {
		return x.Diagnosis
	}
	return ""
}

func (x *AnalyzeClusterResponse) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AnalyzeClusterResponse) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *AnalyzeClusterResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalyzeClusterResponse) GetAnalysisRef() string {
	if x != nil {
		return x.AnalysisRef
	}
	return ""
}

func (x *AnalyzeClusterResponse) GetMemoryKey() string {
	if x != nil {
		return x.MemoryKey
	}
	return ""
}

func (x *AnalyzeClusterResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalyzeClusterResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AnalyzeClusterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnalyzeClusterResponse) GetAnalyzedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnalyzedAt
	}
	return nil
}

var File_kubediscovery_v1_mcp_proto protoreflect.FileDescriptor

const file_kubediscovery_v1_mcp_proto_rawDesc = "" +
	"\n" +
	"\x1akubediscovery/v1/mcp.proto\x12\x10kubediscovery.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x03\n" +
	"\x12ExecuteToolRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\tR\bcallerId\x12(\n" +
	"\x10target_caller_id\x18\x03 \x01(\tR\x0etargetCallerId\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x12!\n" +
	"\fcluster_name\x18\x05 \x01(\tR\vclusterName\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\x125\n" +
	"\targuments\x18\b \x01(\v2\x17.google.protobuf.StructR\targuments\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12=\n" +
	"\frequested_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\xcb\x02\n" +
	"\x13ExecuteToolResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xd5\x03\n" +
	"\x15AnalyzeClusterRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\tR\bcallerId\x12!\n" +
	"\fcluster_name\x18\x03 \x01(\tR\vclusterName\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12#\n" +
	"\rresource_kind\x18\x06 \x01(\tR\fresourceKind\x12#\n" +
	"\rresource_name\x18\a \x01(\tR\fresourceName\x12\x1b\n" +
	"\tpod_phase\x18\b \x01(\tR\bpodPhase\x12\x1b\n" +
	"\tlog_lines\x18\t \x03(\tR\blogLines\x12%\n" +
	"\x0eevent_messages\x18\n" +
	" \x03(\tR\reventMessages\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12=\n" +
	"\frequested_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\xbc\x03\n" +
	"\x16AnalyzeClusterResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1c\n" +
	"\tdiagnosis\x18\x03 \x01(\tR\tdiagnosis\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12(\n" +
	"\x0frecommendations\x18\x05 \x03(\tR\x0frecommendations\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12!\n" +
	"\fanalysis_ref\x18\a \x01(\tR\vanalysisRef\x12\x1d\n" +
	"\n" +
	"memory_key\x18\b \x01(\tR\tmemoryKey\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1d\n" +
	"\n" +
	"error_code\x18\n" +
	" \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x12;\n" +
	"\vanalyzed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"analyzedAt2\xd4\x01\n" +
	"\x11MCPGatewayService\x12Z\n" +
	"\vExecuteTool\x12$.kubediscovery.v1.ExecuteToolRequest\x1a%.kubediscovery.v1.ExecuteToolResponse\x12c\n" +
	"\x0eAnalyzeCluster\x12'.kubediscovery.v1.AnalyzeClusterRequest\x1a(.kubediscovery.v1.AnalyzeClusterResponseB4Z2github.com/kubediscovery/kd-libs/core/v1/mcp;mcpv1b\x06proto3"

var (
	file_kubediscovery_v1_mcp_proto_rawDescOnce sync.Once
	file_kubediscovery_v1_mcp_proto_rawDescData []byte
)

func file_kubediscovery_v1_mcp_proto_rawDescGZIP() []byte {
	file_kubediscovery_v1_mcp_proto_rawDescOnce.Do(func() {
		file_kubediscovery_v1_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubediscovery_v1_mcp_proto_rawDesc), len(file_kubediscovery_v1_mcp_proto_rawDesc)))
	})
	return file_kubediscovery_v1_mcp_proto_rawDescData
}

var file_kubediscovery_v1_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kubediscovery_v1_mcp_proto_goTypes = []any{
	(*ExecuteToolRequest)(nil),     // 0: kubediscovery.v1.ExecuteToolRequest
	(*ExecuteToolResponse)(nil),    // 1: kubediscovery.v1.ExecuteToolResponse
	(*AnalyzeClusterRequest)(nil),  // 2: kubediscovery.v1.AnalyzeClusterRequest
	(*AnalyzeClusterResponse)(nil), // 3: kubediscovery.v1.AnalyzeClusterResponse
	(*structpb.Struct)(nil),        // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_kubediscovery_v1_mcp_proto_depIdxs = []int32{
	4,  // 0: kubediscovery.v1.ExecuteToolRequest.arguments:type_name -> google.protobuf.Struct
	4,  // 1: kubediscovery.v1.ExecuteToolRequest.metadata:type_name -> google.protobuf.Struct
	5,  // 2: kubediscovery.v1.ExecuteToolRequest.requested_at:type_name -> google.protobuf.Timestamp
	4,  // 3: kubediscovery.v1.ExecuteToolResponse.payload:type_name -> google.protobuf.Struct
	4,  // 4: kubediscovery.v1.ExecuteToolResponse.metadata:type_name -> google.protobuf.Struct
	5,  // 5: kubediscovery.v1.ExecuteToolResponse.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 6: kubediscovery.v1.AnalyzeClusterRequest.metadata:type_name -> google.protobuf.Struct
	5,  // 7: kubediscovery.v1.AnalyzeClusterRequest.requested_at:type_name -> google.protobuf.Timestamp
	4,  // 8: kubediscovery.v1.AnalyzeClusterResponse.metadata:type_name -> google.protobuf.Struct
	5,  // 9: kubediscovery.v1.AnalyzeClusterResponse.analyzed_at:type_name -> google.protobuf.Timestamp
	0,  // 10: kubediscovery.v1.MCPGatewayService.ExecuteTool:input_type -> kubediscovery.v1.ExecuteToolRequest
	2,  // 11: kubediscovery.v1.MCPGatewayService.AnalyzeCluster:input_type -> kubediscovery.v1.AnalyzeClusterRequest
	1,  // 12: kubediscovery.v1.MCPGatewayService.ExecuteTool:output_type -> kubediscovery.v1.ExecuteToolResponse
	3,  // 13: kubediscovery.v1.MCPGatewayService.AnalyzeCluster:output_type -> kubediscovery.v1.AnalyzeClusterResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_kubediscovery_v1_mcp_proto_init() }
func file_kubediscovery_v1_mcp_proto_init() {
	if File_kubediscovery_v1_mcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubediscovery_v1_mcp_proto_rawDesc), len(file_kubediscovery_v1_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kubediscovery_v1_mcp_proto_goTypes,
		DependencyIndexes: file_kubediscovery_v1_mcp_proto_depIdxs,
		MessageInfos:      file_kubediscovery_v1_mcp_proto_msgTypes,
	}.Build()
	File_kubediscovery_v1_mcp_proto = out.File
	file_kubediscovery_v1_mcp_proto_goTypes = nil
	file_kubediscovery_v1_mcp_proto_depIdxs = nil
}
