// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: kubediscovery/v1/mcp.proto

package mcpv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MCPGatewayService_ExecuteTool_FullMethodName    = "/kubediscovery.v1.MCPGatewayService/ExecuteTool"
	MCPGatewayService_AnalyzeCluster_FullMethodName = "/kubediscovery.v1.MCPGatewayService/AnalyzeCluster"
)

// MCPGatewayServiceClient is the client API for MCPGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MCPGatewayService defines the contract between kd-mcp and kd-gateway.
type MCPGatewayServiceClient interface {
	// ExecuteTool routes a tool call requested by an MCP client to the target
	// agent connected through kd-gateway.
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
	// AnalyzeCluster requests an on-demand cluster diagnosis handled by
	// kd-analyzer through kd-gateway orchestration.
	AnalyzeCluster(ctx context.Context, in *AnalyzeClusterRequest, opts ...grpc.CallOption) (*AnalyzeClusterResponse, error)
}

type mCPGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPGatewayServiceClient(cc grpc.ClientConnInterface) MCPGatewayServiceClient {
	return &mCPGatewayServiceClient{cc}
}

func (c *mCPGatewayServiceClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, MCPGatewayService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCPGatewayServiceClient) AnalyzeCluster(ctx context.Context, in *AnalyzeClusterRequest, opts ...grpc.CallOption) (*AnalyzeClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeClusterResponse)
	err := c.cc.Invoke(ctx, MCPGatewayService_AnalyzeCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MCPGatewayServiceServer is the server API for MCPGatewayService service.
// All implementations must embed UnimplementedMCPGatewayServiceServer
// for forward compatibility.
//
// MCPGatewayService defines the contract between kd-mcp and kd-gateway.
type MCPGatewayServiceServer interface {
	// ExecuteTool routes a tool call requested by an MCP client to the target
	// agent connected through kd-gateway.
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	// AnalyzeCluster requests an on-demand cluster diagnosis handled by
	// kd-analyzer through kd-gateway orchestration.
	AnalyzeCluster(context.Context, *AnalyzeClusterRequest) (*AnalyzeClusterResponse, error)
	mustEmbedUnimplementedMCPGatewayServiceServer()
}

// UnimplementedMCPGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCPGatewayServiceServer struct{}

func (UnimplementedMCPGatewayServiceServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedMCPGatewayServiceServer) AnalyzeCluster(context.Context, *AnalyzeClusterRequest) (*AnalyzeClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeCluster not implemented")
}
func (UnimplementedMCPGatewayServiceServer) mustEmbedUnimplementedMCPGatewayServiceServer() {}
func (UnimplementedMCPGatewayServiceServer) testEmbeddedByValue()                           {}

// UnsafeMCPGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPGatewayServiceServer will
// result in compilation errors.
type UnsafeMCPGatewayServiceServer interface {
	mustEmbedUnimplementedMCPGatewayServiceServer()
}

func RegisterMCPGatewayServiceServer(s grpc.ServiceRegistrar, srv MCPGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedMCPGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCPGatewayService_ServiceDesc, srv)
}

func _MCPGatewayService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPGatewayServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPGatewayService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPGatewayServiceServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCPGatewayService_AnalyzeCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCPGatewayServiceServer).AnalyzeCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCPGatewayService_AnalyzeCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCPGatewayServiceServer).AnalyzeCluster(ctx, req.(*AnalyzeClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MCPGatewayService_ServiceDesc is the grpc.ServiceDesc for MCPGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubediscovery.v1.MCPGatewayService",
	HandlerType: (*MCPGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTool",
			Handler:    _MCPGatewayService_ExecuteTool_Handler,
		},
		{
			MethodName: "AnalyzeCluster",
			Handler:    _MCPGatewayService_AnalyzeCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kubediscovery/v1/mcp.proto",
}
