// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kubediscovery/v1/executor.proto

package executorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecutorCommand carries a Kubernetes operation request to kd-executor.
type ExecutorCommand struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	RequestId    string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ActionType   string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Source       string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	AnalysisRef  string                 `protobuf:"bytes,4,opt,name=analysis_ref,json=analysisRef,proto3" json:"analysis_ref,omitempty"`
	ClusterName  string                 `protobuf:"bytes,5,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Environment  string                 `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	Namespace    string                 `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResourceKind string                 `protobuf:"bytes,8,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	ResourceName string                 `protobuf:"bytes,9,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Free-form action parameters (for example: replicas, container, tail).
	Params        map[string]string      `protobuf:"bytes,10,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *structpb.Struct       `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorCommand) Reset() {
	*x = ExecutorCommand{}
	mi := &file_kubediscovery_v1_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorCommand) ProtoMessage() {}

func (x *ExecutorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorCommand.ProtoReflect.Descriptor instead.
func (*ExecutorCommand) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_executor_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutorCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutorCommand) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ExecutorCommand) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExecutorCommand) GetAnalysisRef() string {
	if x != nil {
		return x.AnalysisRef
	}
	return ""
}

func (x *ExecutorCommand) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ExecutorCommand) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ExecutorCommand) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExecutorCommand) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

func (x *ExecutorCommand) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ExecutorCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecutorCommand) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecutorCommand) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

// ExecutorResponse returns execution status and command output.
type ExecutorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	AnalysisRef   string                 `protobuf:"bytes,6,opt,name=analysis_ref,json=analysisRef,proto3" json:"analysis_ref,omitempty"`
	ClusterName   string                 `protobuf:"bytes,7,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Environment   string                 `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	Namespace     string                 `protobuf:"bytes,9,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ResourceKind  string                 `protobuf:"bytes,10,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	ResourceName  string                 `protobuf:"bytes,11,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorResponse) Reset() {
	*x = ExecutorResponse{}
	mi := &file_kubediscovery_v1_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorResponse) ProtoMessage() {}

func (x *ExecutorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kubediscovery_v1_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorResponse.ProtoReflect.Descriptor instead.
func (*ExecutorResponse) Descriptor() ([]byte, []int) {
	return file_kubediscovery_v1_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutorResponse) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ExecutorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecutorResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecutorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecutorResponse) GetAnalysisRef() string {
	if x != nil {
		return x.AnalysisRef
	}
	return ""
}

func (x *ExecutorResponse) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ExecutorResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ExecutorResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExecutorResponse) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

func (x *ExecutorResponse) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ExecutorResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecutorResponse) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

var File_kubediscovery_v1_executor_proto protoreflect.FileDescriptor

const file_kubediscovery_v1_executor_proto_rawDesc = "" +
	"\n" +
	"\x1fkubediscovery/v1/executor.proto\x12\x10kubediscovery.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x04\n" +
	"\x0fExecutorCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12!\n" +
	"\fanalysis_ref\x18\x04 \x01(\tR\vanalysisRef\x12!\n" +
	"\fcluster_name\x18\x05 \x01(\tR\vclusterName\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\x12#\n" +
	"\rresource_kind\x18\b \x01(\tR\fresourceKind\x12#\n" +
	"\rresource_name\x18\t \x01(\tR\fresourceName\x12E\n" +
	"\x06params\x18\n" +
	" \x03(\v2-.kubediscovery.v1.ExecutorCommand.ParamsEntryR\x06params\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\x123\n" +
	"\asent_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x03\n" +
	"\x10ExecutorResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12!\n" +
	"\fanalysis_ref\x18\x06 \x01(\tR\vanalysisRef\x12!\n" +
	"\fcluster_name\x18\a \x01(\tR\vclusterName\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x12\x1c\n" +
	"\tnamespace\x18\t \x01(\tR\tnamespace\x12#\n" +
	"\rresource_kind\x18\n" +
	" \x01(\tR\fresourceKind\x12#\n" +
	"\rresource_name\x18\v \x01(\tR\fresourceName\x123\n" +
	"\bmetadata\x18\f \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12;\n" +
	"\vexecuted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAtB>Z<github.com/kubediscovery/kd-libs/core/v1/executor;executorv1b\x06proto3"

var (
	file_kubediscovery_v1_executor_proto_rawDescOnce sync.Once
	file_kubediscovery_v1_executor_proto_rawDescData []byte
)

func file_kubediscovery_v1_executor_proto_rawDescGZIP() []byte {
	file_kubediscovery_v1_executor_proto_rawDescOnce.Do(func() {
		file_kubediscovery_v1_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubediscovery_v1_executor_proto_rawDesc), len(file_kubediscovery_v1_executor_proto_rawDesc)))
	})
	return file_kubediscovery_v1_executor_proto_rawDescData
}

var file_kubediscovery_v1_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kubediscovery_v1_executor_proto_goTypes = []any{
	(*ExecutorCommand)(nil),       // 0: kubediscovery.v1.ExecutorCommand
	(*ExecutorResponse)(nil),      // 1: kubediscovery.v1.ExecutorResponse
	nil,                           // 2: kubediscovery.v1.ExecutorCommand.ParamsEntry
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_kubediscovery_v1_executor_proto_depIdxs = []int32{
	2, // 0: kubediscovery.v1.ExecutorCommand.params:type_name -> kubediscovery.v1.ExecutorCommand.ParamsEntry
	3, // 1: kubediscovery.v1.ExecutorCommand.metadata:type_name -> google.protobuf.Struct
	4, // 2: kubediscovery.v1.ExecutorCommand.sent_at:type_name -> google.protobuf.Timestamp
	3, // 3: kubediscovery.v1.ExecutorResponse.metadata:type_name -> google.protobuf.Struct
	4, // 4: kubediscovery.v1.ExecutorResponse.executed_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kubediscovery_v1_executor_proto_init() }
func file_kubediscovery_v1_executor_proto_init() {
	if File_kubediscovery_v1_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubediscovery_v1_executor_proto_rawDesc), len(file_kubediscovery_v1_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubediscovery_v1_executor_proto_goTypes,
		DependencyIndexes: file_kubediscovery_v1_executor_proto_depIdxs,
		MessageInfos:      file_kubediscovery_v1_executor_proto_msgTypes,
	}.Build()
	File_kubediscovery_v1_executor_proto = out.File
	file_kubediscovery_v1_executor_proto_goTypes = nil
	file_kubediscovery_v1_executor_proto_depIdxs = nil
}
