-- Create clusters table to persist registered Kubernetes clusters managed by the platform.
-- uid is a UUID primary key generated by the application on registration.
CREATE TABLE IF NOT EXISTS clusters (
    uid         UUID        PRIMARY KEY,
    name        TEXT        NOT NULL,
    environment TEXT        NOT NULL,
    status      TEXT        NOT NULL DEFAULT 'active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clusters_environment ON clusters (environment);
CREATE INDEX IF NOT EXISTS idx_clusters_status      ON clusters (status);
